import { defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "cta", title: "CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "availability",
      title: "Availability chip",
      type: "string",
      group: "hero",
      description: "e.g. 'Taking on projects · Q3 2026'. Leave blank to hide.",
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero eyebrow",
      type: "string",
      group: "hero",
      description: "Short mono-style label above the title (e.g. '> freelance dev · ottawa').",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero image (light mode)",
      type: "imageWithAlt",
      group: "hero",
      description: "Shown in light mode. Also used as the dark-mode fallback if no dark variant is set.",
    }),
    defineField({
      name: "heroImageDark",
      title: "Hero image (dark mode)",
      type: "imageWithAlt",
      group: "hero",
      description: "Optional. Shown when the site is in dark mode. Falls back to the light variant if empty.",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero subtitle",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroPrimaryButtonText",
      title: "Primary button text",
      type: "string",
      group: "hero",
      description: "Label for the first hero button (e.g. \"See the work\"). Links to /work.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroSecondaryButtonText",
      title: "Secondary button text",
      type: "string",
      group: "hero",
      description: "Label for the second hero button (e.g. \"Start a project →\"). Links to /contact.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ctaEyebrow",
      title: "CTA eyebrow",
      type: "string",
      group: "cta",
      description: "Short mono-style label above the CTA heading (e.g. \"// let's build\").",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ctaHeading",
      title: "CTA heading",
      type: "string",
      group: "cta",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ctaBody",
      title: "CTA body",
      type: "text",
      rows: 2,
      group: "cta",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ctaButtonText",
      title: "CTA button text",
      type: "string",
      group: "cta",
      description: "Label for the primary button (e.g. \"Start a project →\"). Links to /contact.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Home Page" }),
  },
});
