import { defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "services", title: "Services" },
    { name: "projects", title: "Featured projects" },
    { name: "about", title: "About" },
    { name: "cta", title: "CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Hero eyebrow",
      type: "string",
      group: "hero",
      description: "Short mono-style label above the title (e.g. '> freelance dev · ottawa').",
    }),
    defineField({
      name: "heroTitle",
      title: "Hero title",
      type: "string",
      group: "hero",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero subtitle",
      type: "text",
      rows: 3,
      group: "hero",
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "imageWithAlt",
      group: "hero",
    }),
    defineField({
      name: "availability",
      title: "Availability chip",
      type: "string",
      group: "hero",
      description: "e.g. 'Taking on projects · Q3 2026'. Leave blank to hide.",
    }),
    defineField({
      name: "intro",
      title: "Intro paragraph",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }] }],
      group: "services",
      description: "Short paragraph above the service tiers.",
    }),
    defineField({
      name: "tiers",
      title: "Service tiers",
      type: "array",
      of: [{ type: "serviceTier" }],
      group: "services",
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: "featuredProjects",
      title: "Featured projects",
      type: "array",
      of: [{ type: "reference", to: [{ type: "project" }] }],
      group: "projects",
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: "aboutHeading",
      title: "About heading",
      type: "string",
      group: "about",
    }),
    defineField({
      name: "aboutBody",
      title: "About body",
      type: "array",
      of: [{ type: "block" }],
      group: "about",
    }),
    defineField({
      name: "ctaHeading",
      title: "CTA heading",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaBody",
      title: "CTA body",
      type: "text",
      rows: 2,
      group: "cta",
    }),
    defineField({
      name: "body",
      title: "Legacy body",
      type: "array",
      of: [{ type: "block" }, { type: "imageWithAlt" }],
      group: "about",
      hidden: true,
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Home Page" }),
  },
});
